### ISSUE TITLE
Can expand to generals

### ISSUE THREAD

**Issue by ColdSauce** [TheThirdOne/card-counter#1]
I think it would be really beneficial if one could also have a thing that would show where the other player's general is. Once you found it, it highlights it in the fog of war.

Never forget your enemy general's position again!

**Comment by TheThirdOne** [comment]
Absolutely, that is significantly beyond our current design, but it shouldn't be too hard to add. Additionally, highlighting which "moutain/cities" are cities would be helpful and which squares don't have a capital (or alternatively just the maximum you have explored).

I would be open to a pull request.
